version: "3.9"

services:

    traefik:
        hostname: '{{.Node.Hostname}}-traefik'
        image: traefik:v2.2
        networks:
            - server_network
            - node_network
        dns: 9.9.9.9
        deploy:
            mode: global
            placement:
                constraints:
                    - node.role == manager
            restart_policy:
                condition: any
            update_config:
                order: start-first
                parallelism: 1
            labels:
                - "traefik.enable=true"
                - "traefik.http.middlewares.redirector.redirectScheme.scheme=https"
                - "traefik.http.middlewares.redirector.redirectScheme.permanent=true"
                - "traefik.http.services.httpsredirect.loadbalancer.server.port=80"
                - "traefik.http.routers.httpsredirect.rule=HostRegexp(`{host:.+}`)"
                - "traefik.http.routers.httpsredirect.entryPoints=web"
                - "traefik.http.routers.httpsredirect.middlewares=redirector"
                - "traefik.http.routers.httpsredirect.priority=1000"
        command:
            - "--log.level=INFO"
            - "--api.insecure=false"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--providers.docker.swarmMode=true"
            - "--providers.docker.network=server_network"
            - "--providers.docker.swarmModeRefreshSeconds=1"
            - "--entrypoints.web.address=:80"
            - "--entrypoints.websecure.address=:443"
            - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
            - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
            - "--certificatesresolvers.myresolver.acme.email=team@hutsix.com.au"
            - "--certificatesresolvers.myresolver.acme.storage=/acme/acme.json"
            - "--entryPoints.metrics.address=:8082"
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - traefik-data:/acme
networks:
    server_network:
        name: server_network
        driver: overlay
    node_network:
        name: node_network
        driver: overlay

volumes:
    traefik-data:
    agent-data:
